In [4]:
import numpy as np

In [5]:
def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.2, head_length=0.3, length_includes_head=True,
              **options)

In [44]:
A1 = np.array([[23, 50],[7,  12]])
A2 = np.array([[75, 21],[57, 12]])
A3 = np.array([[57, 67],[99, 43]])
A4 = np.array([[87, 26],[18, 84]])


In [43]:
tensor = np.array ([[A1,A2],[A3,A4]])

tensor

array([[[[23, 50],
         [ 7, 12]],

        [[75, 21],
         [57, 12]]],


       [[[57, 67],
         [99, 43]],

        [[87, 26],
         [18, 84]]]])

In [41]:
tensor.shape

(2, 2, 2, 2)

In [47]:
A = np.array([[23, 50, 19], [7, 12, 109], [57, 67,98]])
B = np.array([17, 22, 19])

In [48]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [49]:
B

array([17, 22, 19])

In [50]:
A * B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

In [51]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [52]:
np.linalg.det(A)

131344.0000000002

In [54]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])