In [32]:
import numpy as np
from numpy.linalg import eig

In [33]:
def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.2, head_length=0.3, length_includes_head=True,
              **options)

In [34]:
A = np.array([1,3])
B = np.array([[1, -1], [6, -4]])

In [35]:

a,b = np.linalg.eig(B)
a

array([-1., -2.])

In [36]:
b

array([[0.4472136 , 0.31622777],
       [0.89442719, 0.9486833 ]])

In [37]:
A/np.linalg.norm(A)

array([0.31622777, 0.9486833 ])